name: queuetodo
description: Manage your everyday tasks in the right order.

version: 1.1.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^1.4.1
  intl: ^0.16.0
  shared_preferences: ^0.5.6+1
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en-US.json
    - assets/lang/pl-PL.json
