name: queuetodo
description: Manage your everyday tasks in the right order.
homepage: https://gitlab.com/mattmaniak/queuetodo

version: 1.3.0+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0
  shared_preferences: ^0.5.6+1
  url_launcher: ^5.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/pl.json
